### ISSUE TITLE
Move ghas-to-csv to advanced-security org

### ISSUE THREAD

**Issue by some-natalie** [advanced-security/ghas-to-csv#36]
```[tasklist]
### Tasks
- [ ] Open OSPO issue and add catalog entry
- [ ] Tidy up any open issues
- [ ] Add community health files
- [ ] Investigate the Flat data error message
- [ ] Any small updates
- [ ] Dependabot, etc. all configured
- [ ] (maybe more)?
```
